### ISSUE TITLE
can i have english definjected files?

### ISSUE THREAD

**Issue by alberto64674yt** [DenJur/RimwoldAutopsy#9]
im interesed in make a spanish translation for this mod but i see all languages have the definjected folder with translated def xml´s but the english one is missing because i dont know portugues,russian or chinese to use that languages as base and replace the lines to spanish ones can you attach or give me the english ones to translate and publish here? like the russian chinese or portugues ones?

**Comment by DenJur** [comment]
Those fields come from the def files themselves. So you can see English text inline in Defs folder.
